name: Build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout '${{github.repository}}' repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build with Maven
        run: mvn --batch-mode verify deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Trigger 'Publish Maven site report' action
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Publish Maven site report
          repo: whyking/whyking.github.io
          token: ${{secrets.GH_ACTIONS_TOKEN}}
          inputs: '{"trigger-repository":"${{github.repository}}","trigger-ref":"${{github.sha}}"}'

